### PR TITLE
add software generated spdif output via I2S data pin

### PR DESCRIPTION
**Pull request by r3d4**
Reworked commit to better integrate into Ka-Radio32. Almost only needs changes in audio_renderer.c

### CODE REVIEW

**Comment by Vasilis-7** [comment]
Hi. Is it working the SPDIF out?

**Comment by marcinmaster999** [comment]
spdif works directly without vs1053 so only soft mp3 works and you hear
crackling noises when switching channels but sounds works good ;)

wt., 18 sie 2020 o 08:40 Vasilis-7 <notifications@github.com> napisał(a):

**Comment by Vasilis-7** [comment]
Thank you for your answer.
So, I will attach an optical Transmitter at the I2S data pin.
What will be the choice for the audio output, in the web interface of KaRadio ?

**Comment by marcinmaster999** [comment]
VID_20200818_114013.mp4
<https://drive.google.com/file/d/10xXgD4IcJeohxMoWrpPTvKGZ0CTqbRKO/view?usp=drive_web>
and link to video.best regards ;)

wt., 18 sie 2020 o 11:35 m bla <marcinmaster999@gmail.com> napisał(a):

**Comment by Vasilis-7** [comment]
Thank you.
I need access to your file through Google Drive.
I have send you a request.

Thank you!
Vasilis

**Comment by marcinmaster999** [comment]
ok but i go to work a share later you got my picture? a have a size error

wt., 18.08.2020, 13:22 użytkownik Vasilis-7 <notifications@github.com>
napisał:

**Comment by Vasilis-7** [comment]
Ok. No problem. i will wait.
I cannot understand what are you writing about the picture.

**Comment by Vasilis-7** [comment]
I have n't received any picture.

**Comment by marcinmaster999** [comment]
Output will be chosen on web interface.


wt., 18.08.2020, 13:45 użytkownik Vasilis-7 <notifications@github.com>
napisał:

**Comment by Vasilis-7** [comment]
I have the current version, and i don't have option for SPDIF output.

**Comment by marcinmaster999** [comment]
maybe try this https://github.com/r3d4/Ka-Radio32/tree/SPDIF

śr., 19 sie 2020 o 12:10 Vasilis-7 <notifications@github.com> napisał(a):

**Comment by marcinmaster999** [comment]
or my  https://github.com/marcinmaster999/Karadio32_mod

czw., 20 sie 2020 o 10:06 m bla <marcinmaster999@gmail.com> napisał(a):

**Comment by briankdlee** [comment]
I can choose sound output as SPDIF with the  recent version 1.9 R10. But I wonder how to wire. Can I connect from I2S pin to optical port(i.e. PLT133) directly? Isn't there needed any resistors?

**Comment by r3d4** [comment]
Yes, you can wire PLT133 Pin 3 (VIN) directly to I2S data pin. PLT133 has logic input so no resistor is needed
You also need to connect 3V..5V power supply at PLT Pins 1(GND) and 2 (VCC). 
Also put 100nf ceramic capacitor between VCC and GND direct at PL133 pins.

**Pull request merged**
