### PR TITLE
Adding support for 20x4 and 16x2 I2C displays

### PR DESCRIPTION
**Pull request by h1aji**
I would like to add support for monochrome displays. I am unable to complete it myslef but hoping someone could assist.

**Dependencies**
This addon makes use of the following components (included as submodules):

components/[smbus](https://github.com/DavidAntliff/esp32-smbus)
components/[i2c_lcd](https://github.com/DavidAntliff/esp32-i2c-lcd1602)

### CODE REVIEW

**Comment by h1aji** [comment]
image

How ideally it should look like

**Comment by h1aji** [comment]
@pilnikov any chance to help with this?

**Comment by pilnikov** [comment]
> @pilnikov any chance to help with this?

very different philosophy
the display is considered as an object with certain properties and methods of work, this makes it possible to simplify the work by standardizing the approaches.
line displays do not fit this philosophy, allowing only text to be displayed, and that one in one font.
so in my opinion the best solution is to use them through an addon on your separate controller.

**Comment by h1aji** [comment]
Thanks, I see your point here but its quite useless to have an extra board when esp32 is fully capable of doing the job.

This code compiles fine now, I just need a help with how to display the data now

**Pull request closed without merging**
